<?php

//generated by AutoPHP v0.1

return function($params = array()){

	$ap_N0Oe11Ag = 'dfsdfsf12';


	return array('ret' => 0, 'data' => array(
		'nino' => addslashes($ap_N0Oe11Ag),
	));
}

?>